name: Docker Build and Push

on:
  push:
    branches: [main] 
    paths-ignore:
       - README.md
       - README.zh-CN.md
       - docs/*.md
       - LICENSE

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Extract version label from Dockerfile
      id: extract_version
      run: |
        echo "VERSION=$(grep 'LABEL version=' Dockerfile | sed -e 's/LABEL version="//' -e 's/"$//')" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        file: ./Dockerfile
        push: true
        tags:  |
          feiyuyu/free-dall-e-proxy:latest
          feiyuyu/free-dall-e-proxy:${{ env.VERSION }}

    - name: Logout from Docker Hub
      if: always()
      run: docker logout
