name: Docker Build share-branch and Push

on:
  push:
    branches: [share] 
    paths-ignore:
       - README.md
       - README.zh-CN.md
       - docs
       - LICENSE

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        file: ./Dockerfile
        push: true
        tags:  |
          feiyuyu/free-dall-e-proxy:share

    - name: Logout from Docker Hub
      if: always()
      run: docker logout
